name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test
        
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
